# Generated by Django 4.2.3 on 2024-04-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topla', '0015_alter_ecole_two_factor_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecole',
            name='two_factor_code',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
